config/routes.rb
Rails.application.routes.draw do
  resources :financialinstruments, :realestates, :users, :sessions
  root to: 'financialinstruments#index'
  get '/signup', to: 'users#new'
  delete '/signout', to: 'sessions#destroy'
  get'/signin', to: 'sessions#new'
end  

app/models/real_estate.rb
class RealEstate < ActiveRecord::Base
  belongs_to :financial_instrument
  belongs_to :user
end

app/models/realestate.rb
class Realestate < ActiveRecord::Base
  require 'open-uri'
  before_save :generate_zestimate
  belongs_to :financialinstrument
  belongs_to :user

  def generate_zestimate
    zillow_link = "http://www.zillow.com/webservice/GetSearchResults.htm?#{ENV['ZILLOW_KEY']}&address=#{self.zipaddress}&citystatezip=#{self.zipcity}, #{self.zipstate} #{self.zipcode}"
    encoded_url = URI.encode(zillow_link)
    URI.parse(encoded_url)
    puts encoded_url
    doc = Nokogiri::HTML(open(encoded_url))
    puts "doc #{doc}"
    self.zestimate = doc.css("zestimate amount")[0].children.text.to_i
  end

  def self.sum_of_realestate(current_user)
    @realestates = current_user.realestates
    sum = 0
    @realestates.each do |realestate| 
      sum+= realestate.zestimate
    end
    return sum
  end

end

app/controllers/real_estates_controller.rb
class RealEstatesController < ApplicationController
  before_filter :signed_in_user, only: [:create, :new, :edit, :update, :destroy]

  def index
    @real_esates = Real_estate.all
  end

  def new
    @real_estate= Real_estate.new
  end

  def create
    real_estate= Real_estate.create(real_estate_params)
    redirect_to real_estate
  end

  def show
    @real_estate = Real_estate.find(params[:id])
  end

  def edit
    @real_estate = Real_estate.find(params[:id])
  end

  def update
    real_estate = Real_estate.find(params[:id])
    real_estate.update_attributes(real_estate_params)
    redirect_to(real_estate)
  end

  def destroy
    real_estate = Real_estate.find(params[:id])
    real_estate.delete
    redirect_to real_estates_path
  end

  private
    def real_estate_params
      params.require(:real_estate).permit(:zipaddress, :zipcity, :zipcode, :zipid, :zestimate, :zillow_link)
    end

end

app/controllers/realestates_controller.rb
class RealestatesController < ApplicationController
  #require 'open-uri'
  include RealestatesHelper


  before_filter :signed_in_user, only: [:create, :new, :edit, :show, :update, :destroy, :index]
  before_filter :load_instrument, only: [:show, :edit, :update, :destroy]

  def index
    @realestates = current_user.realestates
    @realsum = Realestate.sum_of_realestate(current_user)
  end

  def new
    @realestate = Realestate.new
  end

  def create
    realestate = current_user.realestates.create realestate_params
    #zillow_link = "http://www.zillow.com/webservice/GetSearchResults.htm?#{ENV['ZILLOW_KEY']}&address=#{realestate.zipaddress}&citystatezip=#{realestate.zipcity}, #{realestate.zipstate} #{realestate.zipcode}"
    #doc = Nokogiri::HTML(open(zillow_link))
    #realestate.zestimate = doc.css("zestimate amount")[0].children.text.to_i
    if realestate.save
      redirect_to realestate
    else
      flash[:error] = "The real estate property could not be saved.  Try again"
      redirect_to root_path
   end


  end

  def show
   # @real_estates = @financial_instrument.real_estates
  end

  def edit
  end

  def update
    @realestate.update_attributes realestate_params
    redirect_to(@realestate)
  end

  def destroy
    @realestate.delete
    redirect_to(realestates_path)
  end

  private
    def realestate_params
      params.require(:realestate).permit(:zipaddress, :zipcity, :zipstate, :zipcode, :zipid, :zestimate, :zillow_link)
    end
    def load_instrument
      @realestate = Realestate.find(params[:id])
      redirect_to root_path unless @realestate.user == current_user
    end
end

app/helpers/real_estates_helper.rb
module RealEstatesHelper
end

app/helpers/realestates_helper.rb
module RealestatesHelper
  # def check_realestates_owner
  #   # realestate = current_user.financialinstruments.realestates.where(:id => params[:id]).first
  #   # if realestate.nil?
  #   #   flash[:error] = "That's not your real esate property."
  #   #   redirect_to realestate(params[:id])
  #   # end
  # end
end

app/views/realestates/_form.html.erb
<%= form_for @realestate do |f| %>
  <%= f.label :zipaddress%>
  <%= f.text_field :zipaddress, :autofocus => true %>
  <br>
  <p>
  <%= f.label :zipcity%>
  <%= f.text_field :zipcity, :autofocus => true %>
  <br>
    <p>
  <%= f.label :zipstate%>
  <%= f.text_field :zipstate, :autofocus => true %>
  <br>
  <p>
  <%= f.label :zipcode%>
  <%= f.text_field :zipcode, :autofocus => true %>
  <br>
  <p>
  <%= f.submit  class: "btn btn-primary" %>
<% end %>

app/views/realestates/edit.html.erb
<h1>Edit Real Estate Property Info</h1>
<%= render :partial => 'form' %>

app/views/realestates/index.html.erb
<h1><%= "The total sum of all properties is #{ActionView::Base.new.number_to_currency @realsum}" %></h1>
  <table class="table table-hover">
<% @realestates.each do |realestate| %>
  <tr>
      <td><%= link_to(realestate.zipaddress, realestate) %></td>
      <td><%= realestate.zipaddress %></td>
      <td><%= realestate.zipcity %></td>
      <td><%= realestate.zipcode %></td>
      <td><%= ActionView::Base.new.number_to_currency realestate.zestimate %></td>
  </tr>
<% end %>
  </table>

app/views/realestates/new.html.erb
<h1>New Account</h1>
<%= render :partial => 'form' %>

app/views/realestates/show.html.erb
<ul class="nav nav-pills">
  <ul><%= link_to('New Real Estate Property', new_realestate_path) %></ul>
  <br>
  <ul><%= link_to('Edit Real Estate Property', edit_realestate_path(@realestate)) %></ul>
  <br>
   <ul> <%= link_to('Delete Real Estate Property', @realestate, :method => :delete, :confirm => 'Are you sure?') %></ul>
  <div class='spacer'></div>
</ul>