config/routes.rb
Rails.application.routes.draw do
  resources :financialinstruments, :realestates, :users, :sessions
  root to: 'financialinstruments#index'
  get '/signup', to: 'users#new'
  delete '/signout', to: 'sessions#destroy'
  get'/signin', to: 'sessions#new'
end  

app/models/financial_instrument.rb
class FinancialInstrument < ActiveRecord::Base
  belongs_to :user
end

app/models/financialinstrument.rb
class Financialinstrument < ActiveRecord::Base
  belongs_to :user
  
  def self.balancesheet(current_user)
    @financialinstruments = current_user.financialinstruments
    sum = 0
    @financialinstruments.each do |financialinstrument| 
      if financialinstrument.instrument_type == "asset"
        sum+= financialinstrument.amount
      elsif financialinstrument.instrument_type == "liability"
        sum-= financialinstrument.amount
      end
      end
    return sum
  end
  def self.incomestatement(current_user)
    @financialinstruments = current_user.financialinstruments
    sum = 0
    @financialinstruments.each do |financialinstrument| 
      if financialinstrument.instrument_type == "income"
        sum+= financialinstrument.amount
      elsif financialinstrument.instrument_type == "expense"
        sum-= financialinstrument.amount
      end
      end
    return sum
  end
end

app/controllers/financial_instruments_controller.rb
class FinancialInstrumentsController < ApplicationController
  include FinancialInstrumentsHelper

  before_filter :signed_in_user, only: [:create, :new, :edit, :update, :destroy]
  before_filter :check_financial_instrument_owner, only: [:edit, :update, :destroy]

  def index
    @financialinstruments= FinancialInstrument.all
  end

  def new
    @financialinstrument = FinancialInstrument.new
  end

  def create
    financialinstrument = FinancialInstrument.create financial_instrument_params
    redirect_to(financial_instrument)
  end

  def show
    @financialinstrument = FinancialInstrument.find(params[:id])
    @real_estates = @financialinstrument.real_estates
  end

  def edit
    @financialinstrument = FinancialInstrument.find(params[:id])
  end

  def update
    financialinstrument = FinancialInstrument.find(params[:id])
    financialinstrument.update_attributes financialinstrument_params
    redirectto(financialinstrument)
  end

  def destroy
    financialinstrument = FinancialInstrument.find(params[:id])
    financialinstrument.delete
    redirect_to(financialinstruments_path)
  end

  private
    def financialinstrument_params
      params.require(:financialinstrument).permit(:instrument_type, :instrument_sub, :amount)
    end
end

app/controllers/financialinstruments_controller.rb
class FinancialinstrumentsController < ApplicationController
  include FinancialinstrumentsHelper

  before_filter :signed_in_user, only: [:create, :new, :edit, :show, :update, :destroy, :index]
  before_filter :load_instrument, only: [:show, :edit, :update, :destroy]

  def index
    @financialinstruments = current_user.financialinstruments.order(:amount).reverse_order
    @financialbalancesheet = Financialinstrument.balancesheet(current_user)
    @financialincomestatement = Financialinstrument.incomestatement(current_user)
  end

  def new
    @financialinstrument = Financialinstrument.new
  end

  def create
    financialinstrument = current_user.financialinstruments.create(financialinstrument_params)
    if financialinstrument.save
      redirect_to financialinstrument
    else
      flash[:error] = "The financial instrument could not be saved.  Try again"
      redirect_to root_path
   end
 
  end

  def show
  end

  def edit
  end

  def update
    @financialinstrument.update_attributes financialinstrument_params
    redirect_to(@financialinstrument)
  end

  def destroy
    @financialinstrument.delete
    redirect_to(financialinstruments_path)
  end

  private
    def financialinstrument_params
      params.require(:financialinstrument).permit(:instrument_type, :instrument_sub, :amount)
    end

    def load_instrument
      @financialinstrument = Financialinstrument.find(params[:id])
      redirect_to root_path unless @financialinstrument.user == current_user
    end
end

app/helpers/financial_instruments_helper.rb
module FinancialInstrumentsHelper
  #   def check_financial_instruments_owner
  #   financial_instruments = current_user.financial_instruments.where(:id => params[:id]).first
  #   if financial_instrument.nil?
  #     flash[:error] = "That's not your financial instrument."
  #     redirect_to financial_instrument(params[:id])
  #   end
  # end
end

app/helpers/financialinstruments_helper.rb
module FinancialinstrumentsHelper

end

app/views/financialinstruments/_form.html.erb
<%= form_for @financialinstrument do |f| %>

  <%= f.label :instrument_type%>
  <div id="instrument_type">
  <%= f.select :instrument_type, [['asset', "asset"], ['liability', "liability"], ['income', "income"],['expense', "expense"]] %>
</div>
<br>
<div id="instrument_sub">
  <%= f.label :instrument_sub %>
  <%= f.select :instrument_sub, [["savings account", "savings account"], ["checking account", "checking account"], ['taxable investment account', "taxable investment account"], ["IRA Account", "IRA Account"], ["student loan", "student loan"], ["car loan", "car loan"], ['home loan', "home loan"], ["personal loan", "line of credit"], ["salary", "salary"], ["business", "business"], ["contract for hire", "contract for hire"], ["gift", "gift"], ["pension", "pension"], ["rent", "rent"], ["car lease", "lease"], ["household expense", "household expense"], ["other expense", "other expense"]] %>
</div>
<br>
  <%= f.label :amount %>
  <%= f.text_field :amount %>
  <br>
  <p>
  <%= f.submit  class: "btn btn-primary" %>
<% end %>

app/views/financialinstruments/edit.html.erb
<h1>Edit Accounts</h1>
<%= render :partial => 'form' %>

app/views/financialinstruments/index.html.erb
<h1><%= "Your current account balance is #{ActionView::Base.new.number_to_currency @financialbalancesheet}" %></h1>
<table class="table table-hover">
<% @financialinstruments.each do |financialinstrument| %><tr>
      <% if financialinstrument.instrument_type == "asset" || financialinstrument.instrument_type == "liability" %>
      <td><%= link_to(financialinstrument.instrument_sub, financialinstrument) %></td>
      <td><%= financialinstrument.instrument_type %></td>
      <td><%= financialinstrument.instrument_sub %></td>
      <td><%= ActionView::Base.new.number_to_currency financialinstrument.amount %></td>
		<% end %>
    </tr>
		<% end %>
</table>


<h1><%= "Your expected monthly cash inflow is #{ActionView::Base.new.number_to_currency @financialincomestatement}" %></h1>
<table class="table table-hover">
			<% @financialinstruments.each do |financialinstrument| %><tr>
      <% if financialinstrument.instrument_type == "income" || financialinstrument.instrument_type == "expense" %>
      <td><%= link_to(financialinstrument.instrument_sub, financialinstrument) %></td>
      <td><%= financialinstrument.instrument_type %></td>
      <td><%= financialinstrument.instrument_sub %></td>
      <td><%= ActionView::Base.new.number_to_currency financialinstrument.amount %></td>
      <% end %>
    </tr>
<% end %>
</table>

app/views/financialinstruments/show.html.erb
<ul class="nav nav-pills">
  <li><%= link_to('New Account', new_financialinstrument_path) %></li>
  <li><%= link_to('Edit Account', edit_financialinstrument_path(@financialinstrument)) %></li>
  <li>
  <%= link_to('Delete Account', @financialinstrument, :method => :delete, :confirm => 'Are you sure?') %>
</li>
  <div class='spacer'></div>
</ul>