config/routes.rb
Rails.application.routes.draw do
  resources :financialinstruments, :realestates, :users, :sessions
  root to: 'financialinstruments#index'
  get '/signup', to: 'users#new'
  delete '/signout', to: 'sessions#destroy'
  get'/signin', to: 'sessions#new'
end  

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-header navbar-right"> <!--this is nav bar right -->
    <% if signed_in? %>
      <p class="navbar-text">
        <%= link_to "My profile", current_user %>
      </p>
      <p class="navbar-text">
        <%= link_to "Sign out", signout_path, method: "delete" %>
      </p>
    <% else %>
      <p class="navbar-text">
        <%= link_to "Sign up", signup_path %>
      </p>
      <p class="navbar-text">
        <%= link_to "Sign in", signin_path %>
      </p>
    <% end %>
  </div>
  <div class="navbar-default">
    <ul class="nav navbar-nav">
      <li><%= link_to('My Accounts', financialinstruments_path) %></li>
      <li><%= link_to('My Properties', realestates_path) %></li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>myLTP</title>
   <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
  <script src="http://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
  <script src="http://cdn.oesmith.co.uk/morris-0.4.3.min.js"></script>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">

  <%= render 'layouts/header' %>
    <div class="row">
      <div class="col-md-12 col-sm-12">
        <%flash.each do|key,value|%>
                <div class="alert alert-<%=key%>"> <%=value%> </div>
        <%end%>
        <%= yield %>
      </div>
    </div>
</div>

</body>
</html>